### ISSUE TITLE
Cmd-clicking links launches browser inside archipelago

### ISSUE THREAD

**Issue by andrewmcodes** [npezza93/archipelago#113]
**Describe the bug**
Command+click on a link opens up the website inside of the archipelago app. I am assuming this is not intentional because there is no way to get out of the resulting web instance without quitting the entire app.

**To Reproduce**
1. Run command that will output a url
2. The command I ran was for starting up a nuxt.js server
3. Cmd+click a link in the app and a web browser will launch inside of archipelago

**Expected behavior**
Cmd+click will open the default web browser and point at the selected link.

**Screenshots**
![screen shot 2018-12-27 at 4 09 00 pm](https://user-images.githubusercontent.com/18423853/50494528-c0ec7100-09f1-11e9-9765-9a19e5494cf1.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.2
 - Version 3.0.1

**Comment by npezza93** [comment]
This currently is intended behavior. Use cmd+w to exit the browser window. Perhaps we could make it configurable to open externally or internally.
