### ISSUE TITLE
visor not working as expected

### ISSUE THREAD

**Issue by compostbrain** [npezza93/archipelago#128]
**Describe the bug**
When  i hit the visor hotkey the dropdown that appears is blank and does not have any prompt

**To Reproduce**
1. download using brew cask install ar...
2. open then app and configure use /usr/local/bin/zsh
3. close terminal and reload
4. Hit f1 and a dropdown appears but there is not terminal prompt 

**Expected behavior**
I would get a prompt the same as when I open a regular archipelago window

**Desktop (please complete the following information):**
 - OS: osx mojave
 - Version latest

**Comment by npezza93** [comment]
Hey @compostbrain, thanks for the report! I'll investigate and get a patch out later tonight.

**Comment by npezza93** [comment]
@compostbrain Should be resolved in 3.2.1
