### ISSUE TITLE
Icon not appearing in GNOME

### ISSUE THREAD

**Issue by ZuluBunsen** [npezza93/archipelago#148]
On all builds so far, including the newest (3.3.0), the icon does not appear in GNOME, instead being replaced with one of GNOME's defaults.
![Screenshot from 2019-05-17 10-57-17](https://user-images.githubusercontent.com/21266294/57936945-ec81d200-7892-11e9-9493-82c016764b8f.png)
This appears on both the packaged version and on the AppImage version. I am on Antergos, with kernel version 5.0.11-arch1-1-ARCH, and GNOME shell version 3.32.1.

**Comment by npezza93** [comment]
Hey @ZuluBunsen! Thanks for the report, I'll check it out this weekend.

**Comment by ZuluBunsen** [comment]
Seems to be fixed in the newest version! :)
