### ISSUE TITLE
When packaged with 6.0.0-beta.15 >= the app crashes

### ISSUE THREAD

**Issue by npezza93** [npezza93/archipelago#167]
Upstream issue: https://github.com/electron-userland/electron-builder/issues/4104

**Comment by ncino-cpezza** [comment]
I auto updated my app and now it crashes...

**Comment by npezza93** [comment]
Did you update to 3.6.2 or did you get stuck at 3.6.0 or 3.6.1?

**Comment by ncino-cpezza** [comment]
it tried to update to 3.6.1 and then can't update do i need to uninstall and re install?

**Comment by npezza93** [comment]
If you got stuck at 3.6.0 or 3.6.1 unfortunately you're going to have to grab the 3.6.2 dmg from the releases page and then replace your current app. Your settings wont be lost. 

It was a bug that only appears when electron is built so all tests passed and the app packaged correctly. The only way I found out was after the release was posted and my local copy got auto updated. Whoops
