### ISSUE TITLE
AppImage version does not accept Cyrillic characters as input

### ISSUE THREAD

**Issue by patrakov** [npezza93/archipelago#181]
**Describe the bug**
Trying to input or copy-paste Cyrillic letters has no effect.

**To Reproduce**

Option 1:

1. Configure your system for US + Russian keyboard layout: `setxkbmap -model pc104 -layout us,ru -option grp:alt_shift_toggle`
2. Download, make executable, and run `Archipelago-3.7.0.AppImage`
3. Type `echo `, press and release Alt+Shift to switch the keyboard layout to Russian
4. Press `a`
5. Press and release Alt+Shift again to switch back to US keyboard layout.

Option 2:

1. Download, make executable, and run `Archipelago-3.7.0.AppImage`
2. Copy this command from the bug report into the clipboard: `echo ф`
3. Paste it into the terminal.

**Expected behavior**
`echo ф`

**Actual result**
`echo `

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Locale:**

`$LANG` is set to `ru_RU.UTF-8`.

**Comment by npezza93** [comment]
Could you try on the latest version?

**Comment by patrakov** [comment]
Still broken.

**Comment by npezza93** [comment]
Option 2 outputs the expected result for me on the latest version.

**Comment by patrakov** [comment]
Nope. Only option 2 (copy-paste) is fixed now, direct XKB-based Cyrillic input is still broken. Please reopen.
