### ISSUE TITLE
erro on debian 10

### ISSUE THREAD

**Issue by ghost** [npezza93/archipelago#201]
./Archipelago-3.7.1.AppImage
[1798:0916/163117.180687:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_ArchipKkEjEr/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

**Comment by npezza93** [comment]
Related to https://github.com/electron/electron/issues/17972 and https://github.com/electron-userland/electron-builder/issues/3872

**Comment by npezza93** [comment]
I believe this has been resolved in 3.8.1. Let me know if it hasnt

**Comment by Lucas-bash** [comment]
Hi again, please could you take a look in those iso files I this directory.

https://cdimage.debian.org/cdimage/unofficial/non-free/cd-including-firmware/10.2.0-live+nonfree/amd64/bt-hybrid/

This debian images are with cups printer manager not correctly settle up,
this is an annoying but that make me need to use apt to install it, but my
correctly situation doesn't allow me that. I am a teacher and I work in a
school in Brazil where there's no internet connection which makes have a
huge problem.
Anyway can you please help me to find a way out.

Thank you brother.

Em qua, 27 de nov de 2019 23:59, Nick Pezza <notifications@github.com>
escreveu:
