### ISSUE TITLE
terminal

### ISSUE THREAD

**Issue by bdmorin** [npezza93/archipelago#224]
https://hellricer.github.io/2019/10/05/test-drive-your-terminal.html

This post offered a neat script to showcase your (proverbial) terminal's capabilities. Archipelago easily had the most beautiful colors! A few things that I was surprised was blink didn't work, and underlines weren't working, hyper had all kind of things broken in the same test.

Great work, I look forward to using this terminal!

**Comment by npezza93** [comment]
> blink didn't work

Did you enable it in the settings?

> underlines weren't working
<img width="404" alt="image" src="https://user-images.githubusercontent.com/5059927/67627908-7b781a80-f833-11e9-8945-9a63a66a0fc7.png">

Wasnt experiencing that. What kind of settings are you using?
