### ISSUE TITLE
Settings unavailable, redownload link broken

### ISSUE THREAD

**Issue by johnfelixespinosa** [npezza93/archipelago#243]
**Describe the bug**
Upon startup, popup with error in screenshot below shows.
Settings is unavailable/not showing in Archipelago tab bar.
Assumed a reinstall would solve issues however heroku link is broken.

**Screenshots**
![Screen Shot 2019-11-15 at 12 13 03 PM](https://user-images.githubusercontent.com/17545496/68961994-93431e80-07a1-11ea-9a8e-4812c65801df.png)
![Screen Shot 2019-11-15 at 12 15 00 PM](https://user-images.githubusercontent.com/17545496/68962055-b66dce00-07a1-11ea-8517-25d985a442ce.png)

**Desktop (please complete the following information):**
 - MacOS Mojave 10.14.6

**Comment by johnfelixespinosa** [comment]
I think I solved this by reinstalling through brew, will update

**Comment by npezza93** [comment]
For future me: (https://github.com/GitbookIO/nuts/blob/52c91a66c9269e3dac754c276c10333a966f545f/lib/nuts.js#L132-L195).
Not sure about the start up issue. Do you mind posting the contents of the config file if it exists? `cat ~/Library/Application\ Support/Archipelago/config.json`

**Comment by johnfelixespinosa** [comment]
Sorry for the delay

```{
	"version": "3.8.0",
	"profiles": [
		{
			"id": 1,
			"keybindings": [
				{
					"keystroke": "cmd-left",
					"command": "\\x1bOH"
				},
				{
					"keystroke": "cmd-right",
					"command": "\\x1bOF"
				},
				{
					"keystroke": "alt-delete",
					"command": "\\x1bd"
				},
				{
					"keystroke": "cmd-backspace",
					"command": "\\x1bw"
				},
				{
					"keystroke": "cmd-delete",
					"command": "\\x10B"
				}
			],
			"theme": {},
			"visor": {
				"keybinding": "alt-shift",
				"vibrancy": "medium-light",
				"allowTransparency": true
			},
			"cursorStyle": "bar",
			"cursorBlink": true,
			"fontSize": "19",
			"vibrancy": "dark"
		}
	],
	"activeProfileId": 1
}%

**Comment by npezza93** [comment]
Ok looks like your visor keybinding is weird. `alt-shift` can't be selected as those are just modifier keys. I'll work on making sure we bail out of registering the visor command if the keymap doesn't work. A simple fix is to modify the visor-> keybinding field in that file to be something different for the time being like `alt-shift-v` or something similar. I think the default is `f1`.

**Comment by johnfelixespinosa** [comment]
Thanks Nick, that took care of the error and returned the settings ability for me.

**Comment by npezza93** [comment]
A guard has been put in place to handle bad keybindings on the visor. The download links have also been restored.
