### ISSUE TITLE
Archipelago-3.10.0-1.x86_64 conflicts with file from package zettlr-1.6.0_beta.4-1.x86_64

### ISSUE THREAD

**Issue by cristianovitorino** [npezza93/archipelago#311]
**Describe the bug**
Unable to install Archipelago-3.10.0-1.x86_64.rpm package on Fedora 31 due to conflict with Zetttlr 1.6.0 Beta 4-1.

**To Reproduce**
1. Open a Terminal on the folder where the rpm package was downloaded
2. Type: `sudo dnf localinstall Archipelago-3.10.0.x86_64.rpm -y`
3. Or: `sudo dnf install Archipelago-3.10.0.x86_64.rpm`

**Expected behavior**
Ability to install Archipelago-3.10.0-1.x86_64.rpm package with no conflict with other already installed packages.

**Notes**
Zettlr was also installed without a repository.
The AppImage installs and works, but has very poor performance.

**Screenshots**
![terça-18-fevereiro-2020_15-00-46](https://user-images.githubusercontent.com/57003922/74764883-56d00480-5261-11ea-807e-ed7de989899c.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version: Fedora 31

**Comment by npezza93** [comment]
Please see https://github.com/jordansissel/fpm/issues/1503 or https://github.com/balena-io/etcher/issues/3342
