### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by SolarAquarion** [npezza93/archipelago#42]
## OS Used
- [* ] Linux
- [ ] Mac
- [ ] Windows

**Comment by andrewmcodes** [comment]
Hit Cmd+, and type in the font name under the Font Family title.

**Comment by npezza93** [comment]
I just released 2.0.0 so you can either click the hamburger menu and go to 'Settings' or press `Ctrl+,`.

@andrewmcodes `⌘` is not available on Linux
