### ISSUE TITLE
Window doesn't resize

### ISSUE THREAD

**Issue by andrewmcodes** [npezza93/archipelago#43]
## Expected Behavior
When increasing or decreasing the window size, the text should wrap depending on the amount of available space.
## Actual Behavior
When increasing the window size, extra white space is added rather than filling with text. On decreasing the window size, text in the window disappears with no scroll option. 

Further investigation showed the following error in the resize event listener: 
```TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them```
## Steps to Reproduce
Run a command to produce a large amount of text (ex. `brew update`). When resizing the window, text will disappear or white space will appear.
## OS Used
- [ ] Linux
- [x] Mac
- [ ] Windows

**Comment by npezza93** [comment]
This is an upstream issue that is currently being worked on. https://github.com/xtermjs/xterm.js/issues/622
