### ISSUE TITLE
There is no Find option

### ISSUE THREAD

**Issue by amerritt14** [npezza93/archipelago#46]
## Expected Behavior
cmd + f (or ctrl + f for windows) should allow a user to search the terminal's text for word/words
## Actual Behavior
Nothing
## Steps to Reproduce
Press cmd+f
## OS Used
- [ ] Linux
- [X] Mac
- [ ] Windows

I may poke around with implementing this.

**Comment by andrewmcodes** [comment]
Try using `ctrl-r`
