### ISSUE TITLE
Tab hover causes bottom border to flutter

### ISSUE THREAD

**Issue by ncino-cpezza** [npezza93/archipelago#47]
## Expected Behavior
When hovering over a tab when multiple should not also flutter the bottom border on other tabs

## Actual Behavior
When hovering on another tab all tabs start to flutter the bottom border visibility.

## Steps to Reproduce
Create multiple tabs and hover over the non active one

## OS Used
- [ ] Linux
- [X] Mac
- [ ] Windows

<img width="1083" alt="screen shot 2018-04-26 at 6 22 27 am" src="https://user-images.githubusercontent.com/17617672/39303092-85e88fe6-491a-11e8-99b0-5a61f6189010.png">

**Comment by npezza93** [comment]
I was not able to repro. Reopen if this is still an issue.
