### ISSUE TITLE
Horizontal tab has no close option

### ISSUE THREAD

**Issue by andrewmcodes** [npezza93/archipelago#50]
## Expected Behavior
When opening a horizontal tab with `Cmd+s` will split the terminal in half and allow for the option to close the horizontal tab.
## Actual Behavior
The split terminal does not have an option to close the tab on the bottom. The only way to close the tab is to close the tab on top.
## Steps to Reproduce
Hit `Cmd+s` and try to close the horizontal tab.
## OS Used
- [ ] Linux
- [x] Mac
- [ ] Windows

**Comment by npezza93** [comment]
Type `exit` and that split session will close.
