### ISSUE TITLE
Full featured config example

### ISSUE THREAD

**Issue by rapha8l** [npezza93/archipelago#616]
Hi, 

Thanks for Archipelago
It's very nice, though it lacks a config file example
Thanks

**Comment by npezza93** [comment]
What do you mean? Archipelago has a settings screen and doesnt expose its raw config file to the end user.

**Comment by rapha8l** [comment]
indeed, i missed the scrollbar in the settings window.
the font config was using all the screen, so I tought there was nothing else that could be done through
sorry !
