### ISSUE TITLE
Comand Prompt overlaps with window keys

### ISSUE THREAD

**Issue by chiefpansancolt** [npezza93/archipelago#698]
**Describe the bug**
The first line overlaps with the window prompt buttons

**To Reproduce**
See screenshot

**Expected behavior**
An offset so there is no overlap

**Screenshots**
<img width="1075" alt="Screen Shot 2022-04-08 at 9 53 38 AM" src="https://user-images.githubusercontent.com/5841177/162449990-e7de4e6f-3401-4746-9b6a-89ba9bb67086.png">

**Desktop (please complete the following information):**
 - Version 4.0.0

**Comment by npezza93** [comment]
This can be configured in settings under padding.
