### ISSUE TITLE
Spectron can't download since it's in the private npm repository

### ISSUE THREAD

**Issue by SolarAquarion** [npezza93/archipelago#895]
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@npezza93/spectron/21.0.0/4a294a289142546e1ae4f40aff5548420e347f1ce61e1edb8c80c8384fb8f7be: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/solaraquarion/pkgbuilds/archipelago/src/archipelago-4.3.0/yarn-error.log".

**Comment by npezza93** [comment]
Sepctron is a public repo https://github.com/npezza93/spectron/pkgs/npm/spectron

You. have to setup GitHub as an npm registry.
